### PR TITLE
Accept multiple --group-match for OR search.

### PR DESCRIPTION
**Pull request by ryotarai**
*Description of changes:*

Because [Search query for Google Groups](https://developers.google.com/admin-sdk/directory/v1/guides/search-groups) does not support OR clause, we cannot specify multiple groups especially in `groups` sync method.
This PR makes `--group-match` a slice flag and it works as OR clause.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by NachoNorris** [comment]
@ryotarai Could you show me an example of how would it work as an OR?
I've been trying something like this:
`./ssosync -d -c "credentials.json" -u "my.mail@corp.com" --group-match "email=it-infrastructure@corp.com" "email=it-qa@corp.com" -e ...`

Thanks!

**Comment by zumby** [comment]
@ryotarai  we've tested this on our infra, seems to be working fine. multiple groups created, users are added to these groups correctly

**Comment by ChrisPates** [comment]
The multiple flag approach is fine for cli use but not suitable for lambda. However the desired functionality is being implemented under the feature branch [feature-EnhancedMatch](https://github.com/awslabs/ssosync/tree/feature-EnhancedMatch) and will be released shortly.

**Comment by atmosx** [comment]
> The multiple flag approach is fine for cli use but not suitable for lambda. However the desired functionality is being implemented under the feature branch [feature-EnhancedMatch](https://github.com/awslabs/ssosync/tree/feature-EnhancedMatch) and will be released shortly.

The branch doesn't implement the functionality yet right? Using ` -g "name:System*, name:Engine*"` I'm getting:

```
FATA[0000] googleapi: Error 400: Invalid Input: name:System*,, invalid
```

**Comment by int128** [comment]
Apparently, https://github.com/awslabs/ssosync/pull/176 resolved this issue.

**Pull request closed without merging**
