### PR TITLE
refactor: New features for Serverless Repo and Google Best Practices

### PR DESCRIPTION
**Pull request by katallaxie**
*Issue #, if available:*

*Description of changes:*

- Uses a service role for syncing accounts (domain-wide sync and security improvement)
- Unified logging (allows for JSON, TEXT) (`--log-format`)
- Defining log levels (`--log-level`)
- Adds config abstraction
- Removes Google local auth step
- Automates environment variable and parameter binding
- Unifies parameters
- Removes writing to files in AWS Lambda
- Adds SAM support (future: adding it Serverless Repository)
- Adds [direnv](https://direnv.net/)
- Remove AWS CDK in favour of SAM + SAR

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by leepa** [comment]
The GetUsers() test is removed? Is there a reason for that?

**Comment by katallaxie** [comment]
Yep, because using the ListProvider does not get all users. This is a limitation of our implementation of the SCIM RFC. Furthermore, also all parameters to it like `startIndex` etc, beside `count` are ignored. So, this is using the filter mechanism to get users.

**Comment by derektamsen** [comment]
It is great this will switch from using a g suite user account with 3 legged oauth to using a gcp service account. It was one of the first things I thought of when I was going through the setup process.

I was testing this branch because I also hit the issue mentioned in #1 where > 10 users cased the sync to fail. I noticed the pagination issue is also present in the group sync. I have more than 10 groups listed in aws sso.
```
DEBU[0040] get sso groups                               
DEBU[0040] Getting Groups Page                           startIndex=1
DEBU[0040] Add group to map                              group=some-group-name
# 9 more groups print to debug
DEBU[0040] Last Page obtained                            totalResults=10
```
Once the sync finds the 11th group in google it attempts to create it in aws sso but fails with a 409.
```
FATA[0193] status of http response was 409
```
Does this also need a similar fix that was applied to the user pagination issue where it searches for the group instead of populating a map?

Let me know if I can provide any additional debug data.

**Comment by katallaxie** [comment]
@derektamsen could you test https://github.com/awslabs/ssosync/tree/rate_limit to see if this is a throttling issue?

**Comment by katallaxie** [comment]
@derektamsen can u test this again? it uses a filter in the API. There is a caveat to this. We cannot delete groups anymore, because there is no way to retrieve deleted groups from the Google API.

**Comment by derektamsen** [comment]
@katallaxie Thanks for the update. I was able to progress the group sync farther with the updated group sync method. However, I encountered a new issue. At some point the sync stopped when it did not find the group in aws sso.

I think it might be related to setting an error in `aws.FindUserByEmail()`. It's likely this is set if the group was not found in aws sso, which is expected if the group needs to be created in aws https://github.com/awslabs/ssosync/blob/9d461ec4fe9121ea7db9262b38ece5c4b1bf7d24/internal/aws/client.go#L258-L261 However, the `err` return is handled here https://github.com/awslabs/ssosync/blob/9d461ec4fe9121ea7db9262b38ece5c4b1bf7d24/internal/sync.go#L129-L132 which prohibits the group from later being created at https://github.com/awslabs/ssosync/blob/9d461ec4fe9121ea7db9262b38ece5c4b1bf7d24/internal/sync.go#L139

I am retrying the sync with `gg, _ := s.aws.FindGroupByDisplayName(g.Name)` to see if that is the case.

**Comment by katallaxie** [comment]
@derektamsen https://github.com/awslabs/ssosync/releases/tag/v1.0.0-rc.2

**Comment by derektamsen** [comment]
@katallaxie Sorry found a slight bug with the update. When syncing groups the tool exits after finding the first existing group in the aws sso directory.

```
EBU[0041] get google groups                            
DEBU[0042] Check group                                   group=ExistingGroup
# exit 0
```

https://github.com/awslabs/ssosync/blob/5e10fee7c781806b995735ea6a762f9d3cbc7277/internal/sync.go#L134
Since a group exists, `err = nil` which means the if condition is true. I am trying again with `if err != aws.ErrGroupNotFound && err != nil` and it appears to be syncing. Not sure if that is how you want to solve the bug.

**Comment by katallaxie** [comment]
@derektamsen https://github.com/awslabs/ssosync/releases/tag/v1.0.0-rc.3 yep! I will adapt testing as soon we have tested that everything works as expected. I don't have that big of a setup to test all the cases from the Google side.

**Comment by derektamsen** [comment]
@katallaxie Great! That appears to have fixed everything. I was able to sync users, groups, and group membership from gsuite to aws sso. It is definitely slow, but this is a big improvement as the sync actually completes successfully.

Thanks for your help!

**Pull request merged**
