### PR TITLE
Add flag to allow a group match regexp.

### PR DESCRIPTION
**Pull request by grugnog**
We have a large number of groups, but only a small number that are relevant to AWS SSO. This adds a simple regexp based match that can be used to select which groups to sync.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by katallaxie** [comment]
What do you think about an exclude list rather then using a regex? I have the feeling that this might has a side-effects that are not easy to detect.

**Comment by katallaxie** [comment]
@grugnog first addition is to actively ignore groups and users https://github.com/awslabs/ssosync/commit/0e2fbe744163e5e0de814267c0af4860e875c4fe

**Comment by hristo-ganekov-sumup** [comment]
> What do you think about an exclude list rather then using a regex? I have the feeling that this might has side-effects that are not easy to detect.

Since I am in the same scenario as the OP an option for 'included' in the sync groups is way more useful than creating a list with thousands of groups to exclude

**Comment by gavinelder** [comment]
I am in favour of this approach, currently, we have a standardised group format for granting permissions it would be better to have an explicit mapping of what we want to include and not worry about a new group format we have as a business polluting AWS SSO. 

The example here in this use case is a regexp will capture maybe 20-30 groups which we care about vs the several thousand we do not.

**Comment by Hiryus** [comment]
I'd add that AWS admins may be different than Google admins.
So if groups are added by the Google admins, it's better not to have to ignore them on AWS side too.

**Comment by da3mon-01** [comment]
@grugnog could you resolve the conflicts please?

**Comment by grugnog** [comment]
Rebased branch.

As others have mentioned the ignore function is not really practical for orgs with a lot of users/groups.

I think #16 would help for this use case also, however it could take more effort to keep the include list up-to-date for orgs that already have decent group naming conventions.

**Pull request merged**
