### PR TITLE
feat(include-group): adding include-groups option

### PR DESCRIPTION
**Pull request by hristo-ganekov-sumup**
*Issue #, if available:*

*Description of changes:*
Adding the option to *only* include a specified groups to the sync operation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by m477r1x — APPROVED** [review]

**Comment by paul-pop** [comment]
Any update on when this can be released?

**Comment by kguest** [comment]
Any update on this being released?

**Comment by MarkAtwood** [comment]
Hi, I'm a Principal Engineer in the AWS open source team.  We are reviewing this PR for merge.

**Comment by made2591** [comment]
Follow

**Comment by made2591** [comment]
any update on this?

**Comment by joshuachong** [comment]
Changes looks good. Merging into main.

**Review by joshuachong — APPROVED** [review]
Changes looks good.

**Comment by paul-pop** [comment]
Thanks @joshuachong for merging this, any chance you can trigger a release?

**Comment by made2591** [comment]
is there any update about this? @joshuachong could you kindly trigger a release?

**Comment by oleksandr-gubchenko** [comment]
the new version is still not available on serverless app repository on aws

**Pull request merged**
